# Generated by Django 6.0.1 on 2026-01-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parser_used',
            field=models.CharField(blank=True, choices=[('llamaparse', 'LlamaParse (Modern)'), ('nepali_legal_chunker', 'Nepali Legal Chunker (Preeti)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_type',
            field=models.CharField(blank=True, choices=[('modern', 'Modern Unicode'), ('preeti', 'Preeti/Legacy Font')], max_length=20, null=True),
        ),
    ]
