# Generated by Django 6.0.1 on 2026-01-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_document_parser_used_document_pdf_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sources',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
